"""school module tables

Revision ID: 0c73be0f5ac2
Revises: a4698ee0d5e3
Create Date: 2026-09-25 21:28:56.395544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c73be0f5ac2'
down_revision = 'a4698ee0d5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=20), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('group_code', sa.String(length=20), nullable=True),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('lecturer', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_courses_user_id'), ['user_id'], unique=False)

    op.create_table('school_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_school_events_user_start', ['user_id', 'start_at'], unique=False)

    op.create_table('school_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=20), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('exam_type', sa.String(length=10), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_exams_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_school_exams_user_start', ['user_id', 'start_at'], unique=False)

    op.create_table('school_sync_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('school_sync_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_sync_devices_user_id'), ['user_id'], unique=False)

    op.create_table('school_sync_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('sync_requested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('school_tuition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=20), nullable=False),
    sa.Column('amount_due', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status_text', sa.String(length=255), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'term_code')
    )
    with op.batch_alter_table('school_tuition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_tuition_user_id'), ['user_id'], unique=False)

    op.create_table('school_class_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['school_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_class_meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_class_meetings_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_class_meetings_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_school_class_meetings_user_start', ['user_id', 'start_at'], unique=False)

    op.create_table('school_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['school_sync_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_sync_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_school_sync_runs_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('school_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sync_run_id'], ['school_sync_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_changes_sync_run_id'), ['sync_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_changes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_changes_user_id'))
        batch_op.drop_index(batch_op.f('ix_school_changes_sync_run_id'))

    op.drop_table('school_changes')
    with op.batch_alter_table('school_sync_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_school_sync_runs_user_started')
        batch_op.drop_index(batch_op.f('ix_school_sync_runs_user_id'))

    op.drop_table('school_sync_runs')
    with op.batch_alter_table('school_class_meetings', schema=None) as batch_op:
        batch_op.drop_index('ix_school_class_meetings_user_start')
        batch_op.drop_index(batch_op.f('ix_school_class_meetings_user_id'))
        batch_op.drop_index(batch_op.f('ix_school_class_meetings_course_id'))

    op.drop_table('school_class_meetings')
    with op.batch_alter_table('school_tuition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_tuition_user_id'))

    op.drop_table('school_tuition')
    op.drop_table('school_sync_settings')
    with op.batch_alter_table('school_sync_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_sync_devices_user_id'))

    op.drop_table('school_sync_devices')
    with op.batch_alter_table('school_exams', schema=None) as batch_op:
        batch_op.drop_index('ix_school_exams_user_start')
        batch_op.drop_index(batch_op.f('ix_school_exams_user_id'))

    op.drop_table('school_exams')
    with op.batch_alter_table('school_events', schema=None) as batch_op:
        batch_op.drop_index('ix_school_events_user_start')
        batch_op.drop_index(batch_op.f('ix_school_events_user_id'))

    op.drop_table('school_events')
    with op.batch_alter_table('school_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_courses_user_id'))

    op.drop_table('school_courses')
    # ### end Alembic commands ###
