"""blackboard tables

Revision ID: 25c0593b5109
Revises: 0c73be0f5ac2
Create Date: 2026-09-26 01:40:09.034736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c0593b5109'
down_revision = '0c73be0f5ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_bb_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bb_id', sa.String(length=64), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_bb_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_bb_courses_user_id'), ['user_id'], unique=False)

    op.create_table('school_bb_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('bb_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['school_bb_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_bb_announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_bb_announcements_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_bb_announcements_user_id'), ['user_id'], unique=False)

    op.create_table('school_bb_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('bb_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('points_possible', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade_text', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['school_bb_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_bb_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_bb_assignments_course_id'), ['course_id'], unique=False)
        batch_op.create_index('ix_school_bb_assignments_user_due', ['user_id', 'due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_bb_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('school_bb_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('bb_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['school_bb_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_bb_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_bb_materials_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_bb_materials_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_bb_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_bb_materials_user_id'))
        batch_op.drop_index(batch_op.f('ix_school_bb_materials_course_id'))

    op.drop_table('school_bb_materials')
    with op.batch_alter_table('school_bb_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_bb_assignments_user_id'))
        batch_op.drop_index('ix_school_bb_assignments_user_due')
        batch_op.drop_index(batch_op.f('ix_school_bb_assignments_course_id'))

    op.drop_table('school_bb_assignments')
    with op.batch_alter_table('school_bb_announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_bb_announcements_user_id'))
        batch_op.drop_index(batch_op.f('ix_school_bb_announcements_course_id'))

    op.drop_table('school_bb_announcements')
    with op.batch_alter_table('school_bb_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_bb_courses_user_id'))

    op.drop_table('school_bb_courses')
    # ### end Alembic commands ###
